### ISSUE TITLE
Possible to exclude folders?

### ISSUE THREAD

**Issue by jamesdixon** [Parallels/boot2docker-vagrant-box#16]
Is it possible to exclude folders with Parallels Shared Folders?

I have an Ember application running a local server that watches for file changes in the shared directories.  Unfortunately, sometimes it appears to flip out and think that a ton of files have been changed causing issues. I haven't seen this issue when running it on my machine locally rather than in the VM.

Thanks!
James

**Comment by legal90** [comment]
If you want to exclude all Parallels Shared Folders, just disable these two synced folders:
```ruby
config.vm.synced_folder "/Users", "/Users", disabled: true
config.vm.synced_folder ".", "/vagrant", disabled: true
```
Th first is pre-defined in this box by default (see [vagrantfile.tpl](https://github.com/Parallels/boot2docker-vagrant-box/blob/1efc375b5679f7d452366e0ad67a4a2cd25da899/vagrantfile.tpl)). And the second one is a default shared folder for all Vagrant machines.

As alternative for disabling, you can also override these synced folders with some other type, for example NFS:
```ruby
config.vm.synced_folder "/Users", "/Users", type: "nfs", mount_options: ["nolock", "vers=3", "udp"]
```
