### ISSUE TITLE
Update to 1.5

### ISSUE THREAD

**Issue by Tomdarkness** [Parallels/boot2docker-vagrant-box#7]
I've tried building the box with the 1.5 iso but it does not work properly, seems like something else needs updating as well.

With the 1.5 ISO docker on the host can't connect to docker running in the VM and the provisioned containers don't start with the VM.

**Comment by zfogg** [comment]
+1

**Comment by hadronzoo** [comment]
:+1:

**Comment by zfogg** [comment]
To those patiently waiting.. I  ran out of patience! So I forked this repo and made an updated box :) feel free to use it!

**Note** - there are some slight changes!
* Check out [the README](https://github.com/wearableintelligence/boot2docker-vagrant-box/blob/docker/v1.5.0/README.md) in my fork for details,
* or just view the [diff](https://github.com/wearableintelligence/boot2docker-vagrant-box/compare/Parallels:parallels...parallels).

https://github.com/wearableintelligence/boot2docker-vagrant-box/releases/tag/docker%2Fv1.5.0

**Comment by zchee** [comment]
@zfogg Awesome.
The Parallels team is too slow. lol

**Comment by antmanler** [comment]
+1

**Comment by caseywebdev** [comment]
:+1:

**Comment by AntonioMeireles** [comment]
fwiw i've been maintaining, since @YungSang departure both **coreos-packer** and **boot2docker-vagrant-box** at **[AntonioMeireles/coreos-packer](https://github.com/AntonioMeireles/coreos-packer)** and **[AntonioMeireles/boot2docker-vagrant-box](https://github.com/AntonioMeireles/boot2docker-vagrant-box)**. The matching up to date boxes are here.

**Comment by legal90** [comment]
Done: https://github.com/Parallels/boot2docker-vagrant-box/releases/tag/parallels%2Fv1.5.0

**Comment by caseywebdev** [comment]
:clap:

**Comment by dguerri** [comment]
For the sake of curiosity, why did you remove TLS support?

**Comment by legal90** [comment]
>For the sake of curiosity, why did you remove TLS support?

@YungSang, Could you please remind why it was done?

**Comment by AntonioMeireles** [comment]
@dguerri @legal90 afaict TLS support was removed by @YungSang on his tree (which this one inherits) for the sake of "simplicity".  FWIW [my tree](https://github.com/AntonioMeireles/boot2docker-vagrant-box) supports it out of the box and transparently.

**Comment by dguerri** [comment]
Fair enough :) Thanks for the quick reply
