### ISSUE TITLE
Update to Docker 1.6.0

### ISSUE THREAD

**Issue by hadronzoo** [Parallels/boot2docker-vagrant-box#8]
[Docker 1.6.0 has been released](https://blog.docker.com/2015/04/docker-release-1-6/) and the 1.6 client is incompatible with the 1.5 server.

**Comment by caseywebdev** [comment]
:+1:

**Comment by AaronLasseigne** [comment]
:+1:

**Comment by sean-brandt** [comment]
+1

**Comment by EloB** [comment]
+1

**Comment by legal90** [comment]
Done:  the box `parallels/boot2docker` v1.6.0 has been released:
https://atlas.hashicorp.com/parallels/boxes/boot2docker/versions/1.6.0

---

It still has SSL disabled, because I can't find a good approach for managing CAs on the host side.
For those who are cool enough to help with SSL verification issues, here is `boot2docker.iso` with enabled TLS: https://github.com/Parallels/boot2docker/releases/tag/parallels%2Fv1.6.0-ssl

To boot2docker VM with TLS enabled, we have to specify these export these env 
```bash
export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH="<some_path>"
```
VM generates certificates automatically, so we have to download a CA to the host and manage DOCKER_CERT_PATH somehow. Pull-requests are welcome :-)

**Comment by caseywebdev** [comment]
:boom: thanks!

**Comment by EloB** [comment]
It ask me for password to docker when I ran your latest.

Versions:
- Vagrant 1.7.2
- Parallels 10.2.0

```
$ vagrant up --provider parallels
Bringing machine 'default' up with 'parallels' provider...
==> default: Importing base box 'parallels/boot2docker'...
==> default: Checking if box 'parallels/boot2docker' is up to date...
==> default: Setting the name of the VM: rofl_default_1429474173355_86151
==> default: Preparing network interfaces based on configuration...
    default: Adapter 0: shared
==> default: Clearing any previously set network interfaces...
==> default: Forwarding ports...
    default: 2375 => 2375
==> default: Setting power consumption mode: "Longer battery life"
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 10.211.55.19:22
    default: SSH username: docker
    default: SSH auth method: private key
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
docker@10.211.55.19's password:
```

**Comment by legal90** [comment]
@EloB this is a strange floating issue, which I've faced with too. It doesn't depend on version of box, Vagrant or PDFM.
Password is required occasionally and we can just skip it by multiple pressing "Enter" - the process will be process. After that `vagrant ssh` is working fine, which means that there are no authentication issues. 

I've also figured out that it is not specific to Parallels provider:
https://github.com/mitchellh/vagrant/issues/5153
https://github.com/mitchellh/boot2docker-vagrant-box/issues/79#issuecomment-75563953

**Comment by EloB** [comment]
Okay :+1:

**Comment by nunofgs** [comment]
How do I solve the SSL issue?

Using the official instructions I was able to bring the machine up but then I get this:

```bash
❯ docker ps
FATA[0000] Couldn't read ca cert /Users/xxx/test/.docker/ca.pem: open /Users/xxx/test/.docker/ca.pem: no such file or directory
```

Do I generate the certificate myself and place it there? If so, can someone add clear instructions to the README?

**Comment by legal90** [comment]
@nunofgs TLS is not supported by our box yet (https://github.com/Parallels/boot2docker-vagrant-box/issues/8#issuecomment-94271127)
Please, ensure that env variable `DOCKER_TLS_VERIFY` is unset or equals 0
```
export DOCKER_TLS_VERIFY=0
```
