### ISSUE TITLE
vagrant up asking for password

### ISSUE THREAD

**Issue by boosis** [Parallels/boot2docker-vagrant-box#9]
Fresh install. This is the result of my `vagrant up`

Bringing machine 'boot2docker' up with 'parallels' provider...
==> boot2docker: Importing base box 'parallels/boot2docker'...
==> boot2docker: Checking if box 'parallels/boot2docker' is up to date...
==> boot2docker: Setting the name of the VM: host_boot2docker_1432207690787_92688
==> boot2docker: Preparing network interfaces based on configuration...
    boot2docker: Adapter 0: shared
    boot2docker: Adapter 1: hostonly
==> boot2docker: Clearing any previously set network interfaces...
==> boot2docker: Forwarding ports...
    boot2docker: 2375 => 2375
==> boot2docker: Setting power consumption mode: "Longer battery life"
==> boot2docker: Running 'pre-boot' VM customizations...
==> boot2docker: Booting VM...
==> boot2docker: Waiting for machine to boot. This may take a few minutes...
    boot2docker: SSH address: 10.211.55.15:22
    boot2docker: SSH username: docker
    boot2docker: SSH auth method: private key
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
docker@10.211.55.15's password:

if I wait (or use tcuser as password)

docker@10.211.55.15's password:    boot2docker: Warning: Connection timeout. Retrying...
==> boot2docker: Machine booted and ready!
==> boot2docker: Configuring and enabling network interfaces...
==> boot2docker: Exporting NFS shared folders...
==> boot2docker: Preparing to edit /etc/exports. Administrator privileges will be required...
Password:

Nothing happens after this. Keeps waiting for the password.

vagrant version
Installed Version: 1.7.2
Latest Version: 1.7.2

**Comment by boosis** [comment]
And this is the Vagrant file

Vagrant.configure(2) do |config|
    config.vm.define "boot2docker"
    config.vm.box = "parallels/boot2docker"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.synced_folder "/Users/bill/work", "/work", type: "nfs"
    # Fix busybox/udhcpc issue
    config.vm.provision :shell do |s|
      s.inline = <<-EOT
        if ! grep -qs ^nameserver /etc/resolv.conf; then
          sudo /sbin/udhcpc
        fi
        cat /etc/resolv.conf
      EOT
    end

    # Adjust datetime after suspend and resume
    config.vm.provision :shell do |s|
      s.inline = <<-EOT
        sudo /usr/local/bin/ntpclient -s -h pool.ntp.org
        date
      EOT
    end
end

**Comment by zfogg** [comment]
+1 this occasionally happens for me too. couldn't diagnose why, and couldn't consistently reproduce

**Comment by boosis** [comment]
It happens to me all the time. I couldn't get it working so far.

**Comment by legal90** [comment]
This is a strange floating issue, which I've faced with too. It doesn't depend on version of box, Vagrant or Parallels Desktop.
Password is required occasionally and we can just skip it by multiple pressing "Enter" - the process will be process. After that vagrant ssh is working fine, which means that there are no authentication issues.

I've also figured out that it is not specific to Parallels provider:
mitchellh/vagrant#5153
mitchellh/boot2docker-vagrant-box#79 (comment)

**Comment by boosis** [comment]
@legal90 pressing Enter multiple times does skip the first prompt, but not the second (the one about nfs). 
At the moment, this is unusable for me.

**Comment by legal90** [comment]
@boosis 
> boot2docker: Preparing to edit /etc/exports. Administrator privileges will be required...

It means that Vagrant asks you to enter the password from your account on the Mac host. It is going to use sudo to edit `/etc/exports` on your machine.

**Comment by boosis** [comment]
Holy s...t! I tried all kind of passwords, the only one I didn't try was my own password :) The machine booted up just fine now!


Thanks
